name: model_hub_mmdet_experiment
defaults:
    - data: disk
    - profiling: disabled
    - searcher: single
    - hyperparameters:
        - base

checkpoint_storage:
  save_trial_latest: 5

min_validation_period:
  batches: 7320

environment:
  image:
    gpu: determinedai/model-hub-mmdetection:0.23.3-rc0
  environment_variables:
      - OMP_NUM_THREADS=1 # Following pytorch dtrain, this environment variable is set to 1 to avoid overloading the system.

resources:
  slots_per_trial: 8 # max number of GPUs a trial is allowed to individually use
  shm_size: 200000000000
entrypoint: python3 -m determined.launch.torch_distributed --trial model_hub.mmdetection:MMDetTrial
