global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'det-master'
    scheme: http
    metrics_path: '/debug/prom/det-metrics'
    static_configs:
      - targets:
          - localhost:8080


  - job_name: 'determined-cluster'
    scrape_timeout: 500ms
    file_sd_configs:
      - files:
          - "/etc/determined/targets.json"
        refresh_interval: 30s
    metric_relabel_configs:
      - action: replace
        source_labels: [id]
        target_label: container_runtime_id
        regex: "/docker/(.*)"
      - action: replace
        source_labels: [container_label_ai_determined_container_parent]
        target_label: experiment_id
        regex: "/experiments/(.*)/.*"
      - action: replace
        source_labels: [__name__, UUID]
        regex: 'DCGM.*;(.*)'
        target_label: gpu_uuid