{{- if .Values.genai.version }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
     app: genai-{{ .Release.Name }}
     release: {{ .Release.Name }}
{{ end -}}
