version: 2.1

commands:
  # circleci's checkout does not fetch submodules by default.
  # https://circleci.com/docs/2.0/configuration-reference/#checkout
  checkout-with-sm:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

  install-python:
    steps:
      - run:
          name: Installing Python
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pip


# Define the jobs
jobs:
  test-repo-integration-local:
    docker:
      - image: cimg/node:16.14
    resource_class: xlarge
    steps:
      - checkout
      - install-python
      - run: ./bin/test.py --repos core --test-local

  test-repo-integration-gitsubtree:
    docker:
      - image: cimg/node:16.14
    resource_class: xlarge
    environment:
      - GIT_AUTHOR_NAME: "Tester"
      - GIT_AUTHOR_EMAIL: tester@determined.ai
      - GIT_COMMITTER_NAME: "Tester"
      - GIT_COMMITTER_EMAIL: tester@determined.ai
    steps:
      - checkout
      - install-python
      - run: ./bin/test.py --repos core --sw-hash $CIRCLE_SHA1

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test-repo-integration-local
      - test-repo-integration-gitsubtree
