apiVersion: v1
kind: ServiceAccount
metadata:
  name: determined-master-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
     app: deteremined-master-{{ .Release.Name }}
     release: {{ .Release.Name }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: determined-master-{{ .Release.Name }}
  labels:
     app: deteremined-master-{{ .Release.Name }}
     release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/log", "configmaps"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: determined-master-{{ .Release.Name }}
  labels:
     app: deteremined-master-{{ .Release.Name }}
     release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: determined-master-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: determined-master-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
