checkpoint_storage:
  type: shared_fs
  host_path: /tmp
  storage_path: determined-checkpoint
  save_experiment_best: 0
  save_trial_best: 1
  save_trial_latest: 1

db:
  user: postgres
  host: localhost
  port: 5432
  name: determined
  password: postgres

scim:
  enabled: true
  auth:
    type: basic
    username: determined
    password: password
