name: huggingface_swag_trial
hyperparameters:
  pretrained_model_name_or_path: roberta-base
  model_mode: multiple-choice
  use_pretrained_weights: true
  use_apex_amp: true
  cache_dir: null
  # Training Args
  global_batch_size: 64
  learning_rate: 5.0e-5
  adam_epsilon: 1.0e-8
  weight_decay: 0
  lr_scheduler_type: linear
  num_warmup_steps: 0
data:
  dataset_name: swag
  dataset_config_name: regular
  train_file: null
  validation_file: null
  overwrite_cache: false
  preprocessing_num_workers: null
  max_seq_length: 128
  pad_to_max_length: false
# Number of records per epoch differs based on max_seq_length.
records_per_epoch: 73546
min_validation_period:
  batches: 500
searcher:
  name: single
  metric: accuracy
  max_length:
    epochs: 3
  smaller_is_better: false
environment:
  image: 
   gpu: determinedai/model-hub-transformers:0.19.3-dev0
resources:
  slots_per_trial: 2
# We add a bind_mount here so that cached data, tokenized data, and models will be saved to the
# host_path on the agent instance disk for reuse if the same experiment is run on this instance.
bind_mounts:
  - host_path: /tmp
    container_path: /root/.cache
entrypoint: swag_trial:SWAGTrial
