project_name: determined-helm

build:
  skip: true

release:
  github:
    owner: determined-ai
    name: determined-ee
  mode: keep-existing
  extra_files:
    - glob: build/determined-latest.tgz
      name_template: "determined-helm-chart_{{ .Env.VERSION }}.tgz"

  # be sure to keep this in sync between agent/master/helm
  # the "include" functionality is only in the pro version
  header: |
    ## Release Notes
    [{{ .Tag }}](https://github.com/determined-ai/determined-ee/blob/{{ .Tag }}/docs/release-notes.rst)
