# Metrics differ for different tasks.
# | task | metric               |
# | cola | matthews_correlation |
# | sst2 | accuracy             |
# | mrpc | accuracy or f1       |
# | stsb | pearson or spearmanr |
# | qqp  | accuracy or f1       |
# | mnli | accuracy             |
# | qnli | accuracy             |
# | rte  | accuracy             |
# | wnli | accuracy             |
name: huggingface_glue_trial
hyperparameters:
  pretrained_model_name_or_path: bert-base-cased
  model_mode: sequence-classification
  finetuning_task: cola
  use_pretrained_weights: true
  use_apex_amp: true
  # Training Args
  global_batch_size: 32
  learning_rate: 3.0e-5
  adam_epsilon: 1.0e-8
  weight_decay: 0
  lr_scheduler_type: linear
  num_warmup_steps: 0
data:
  dataset_name: glue
  dataset_config_name: cola
  max_seq_length: 128
  train_file: null
  validation_file: null
  preprocessing_num_workers: null
  cache_dir: null
  overwrite_cache: false
  pad_to_max_length: true
# Number of records per epoch differs based on max_seq_length.
records_per_epoch: 8551
min_validation_period:
  batches: 500
searcher:
  name: single
  metric: matthews_correlation
  max_length:
    epochs: 3
  smaller_is_better: false
environment:
  image: 
    gpu: determinedai/model-hub-transformers:0.23.3-rc0
resources:
  slots_per_trial: 1
# We add a bind_mount here so that cached data, tokenized data, and models will be saved to the
# host_path on the agent instance disk for reuse if the same experiment is run on this instance.
bind_mounts:
  - host_path: /tmp
    container_path: /root/.cache
entrypoint: glue_trial:GLUETrial
