---
name: "Lint react"

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'webui/*'
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  lint-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.1.0
      # Explicitly caching node_modules manually as actions/setup-node does not
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          key: webui/react/node_modules.${{ hashFiles('webui/react/package-lock.json') }}
          path: webui/react/node_modules
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make -C webui/react get-deps-npm
      - name: Run checks
        run: make -C webui/react check
